// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl7O7x21bA_1MB9_my7f8-TdPE6WaHdBQ',
    appId: '1:622454579771:web:01d82ff7b2dc432d24721e',
    messagingSenderId: '622454579771',
    projectId: 'test-flutter-71245',
    authDomain: 'test-flutter-71245.firebaseapp.com',
    storageBucket: 'test-flutter-71245.firebasestorage.app',
    measurementId: 'G-27P5M822WW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4YT6umO4AegPFE5Lz9KyVJcXKf1KH7Jo',
    appId: '1:622454579771:android:6bff24a739fb889324721e',
    messagingSenderId: '622454579771',
    projectId: 'test-flutter-71245',
    storageBucket: 'test-flutter-71245.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXWWr88cEfCbtVl2lECYsF3bXHVLtYs5k',
    appId: '1:622454579771:ios:023206cae70cc51324721e',
    messagingSenderId: '622454579771',
    projectId: 'test-flutter-71245',
    storageBucket: 'test-flutter-71245.firebasestorage.app',
    iosBundleId: 'com.example.journalAppInFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXWWr88cEfCbtVl2lECYsF3bXHVLtYs5k',
    appId: '1:622454579771:ios:023206cae70cc51324721e',
    messagingSenderId: '622454579771',
    projectId: 'test-flutter-71245',
    storageBucket: 'test-flutter-71245.firebasestorage.app',
    iosBundleId: 'com.example.journalAppInFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBl7O7x21bA_1MB9_my7f8-TdPE6WaHdBQ',
    appId: '1:622454579771:web:fc6262f9c6cc0ada24721e',
    messagingSenderId: '622454579771',
    projectId: 'test-flutter-71245',
    authDomain: 'test-flutter-71245.firebaseapp.com',
    storageBucket: 'test-flutter-71245.firebasestorage.app',
    measurementId: 'G-63JDHY60WV',
  );
}
